//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInfoServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://userinfowebservice.guitarcenter.com", ConfigurationName="UserInfoServiceReference.UserInfoWebServiceSoap")]
    public interface UserInfoWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getUserInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getUserInfoTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getUserInfoTestAsync(string s_empID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getDSMDOMLocations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UserInfoServiceReference.ArrayOfXElement> getDSMDOMLocationsAsync(int DOMorDSMID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getEmployeeID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getEmployeeIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getPasswordRegistration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> getPasswordRegistrationAsync(string s_empID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getUserInfoByEmpID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getUserInfoByEmpIDAsync(int empID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getMyEmpIDByAccountName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getMyEmpIDByAccountNameAsync(string accountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getPLCCMembership", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> getPLCCMembershipAsync(string accountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/isLocRetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> isLocRetailAsync(int locID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getDMDistrictId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getDMDistrictIdAsync(int DMID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getRMRegionId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getRMRegionIdAsync(int RMID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://userinfowebservice.guitarcenter.com/getAllStoresSMDMRVP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UserInfoServiceReference.ArrayOfXElement> getAllStoresSMDMRVPAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://userinfowebservice.guitarcenter.com/getMembershipBySAMAccountName", ReplyAction = "*")]

        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]

        System.Threading.Tasks.Task<string[]> getMembershipBySAMAccountNameAsync(string accountName);

    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface UserInfoWebServiceSoapChannel : UserInfoServiceReference.UserInfoWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class UserInfoWebServiceSoapClient : System.ServiceModel.ClientBase<UserInfoServiceReference.UserInfoWebServiceSoap>, UserInfoServiceReference.UserInfoWebServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserInfoWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(UserInfoWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), UserInfoWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserInfoWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserInfoWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserInfoWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserInfoWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserInfoWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getUserInfoAsync()
        {
            return base.Channel.getUserInfoAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getUserInfoTestAsync(string s_empID)
        {
            return base.Channel.getUserInfoTestAsync(s_empID);
        }
        
        public System.Threading.Tasks.Task<UserInfoServiceReference.ArrayOfXElement> getDSMDOMLocationsAsync(int DOMorDSMID)
        {
            return base.Channel.getDSMDOMLocationsAsync(DOMorDSMID);
        }
        
        public System.Threading.Tasks.Task<string> getEmployeeIDAsync()
        {
            return base.Channel.getEmployeeIDAsync();
        }
        
        public System.Threading.Tasks.Task<bool> getPasswordRegistrationAsync(string s_empID)
        {
            return base.Channel.getPasswordRegistrationAsync(s_empID);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getUserInfoByEmpIDAsync(int empID)
        {
            return base.Channel.getUserInfoByEmpIDAsync(empID);
        }
        
        public System.Threading.Tasks.Task<string> getMyEmpIDByAccountNameAsync(string accountName)
        {
            return base.Channel.getMyEmpIDByAccountNameAsync(accountName);
        }
        
        public System.Threading.Tasks.Task<string[]> getPLCCMembershipAsync(string accountName)
        {
            return base.Channel.getPLCCMembershipAsync(accountName);
        }
        
        public System.Threading.Tasks.Task<bool> isLocRetailAsync(int locID)
        {
            return base.Channel.isLocRetailAsync(locID);
        }
        
        public System.Threading.Tasks.Task<string> getDMDistrictIdAsync(int DMID)
        {
            return base.Channel.getDMDistrictIdAsync(DMID);
        }
        
        public System.Threading.Tasks.Task<string> getRMRegionIdAsync(int RMID)
        {
            return base.Channel.getRMRegionIdAsync(RMID);
        }
        
        public System.Threading.Tasks.Task<UserInfoServiceReference.ArrayOfXElement> getAllStoresSMDMRVPAsync()
        {
            return base.Channel.getAllStoresSMDMRVPAsync();
        }
        public System.Threading.Tasks.Task<string[]> getMembershipBySAMAccountNameAsync(string accountName)

        {

            return base.Channel.getMembershipBySAMAccountNameAsync(accountName);

        }
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserInfoWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.UserInfoWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserInfoWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://userinfowebservicedev.guitarcenter.com/UserInfoWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.UserInfoWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://userinfowebservicedev.guitarcenter.com/UserInfoWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            UserInfoWebServiceSoap,
            
            UserInfoWebServiceSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
